const ReviewsActionsConstants = {
    LOAD_REVIEWS_ACTION:         'LOAD_REVIEWS_ACTION',
    LOAD_REVIEWS_ACTION_SUCCESS: 'LOAD_REVIEWS_ACTION_SUCCESS',
    LOAD_REVIEWS_ACTION_FAILURE: 'LOAD_REVIEWS_ACTION_FAILURE',

    ADD_REVIEW_ACTION: 'ADD_REVIEW_ACTION',
    EDIT_REVIEW_ACTION: 'EDIT_REVIEW_ACTION',
    ADD_REVIEW_ACTION_SUCCESS: 'ADD_REVIEW_ACTION_SUCCESS',
    ADD_REVIEW_ACTION_FAILURE: 'ADD_REVIEW_ACTION_FAILURE',
    DELETE_REVIEW_ACTION: 'DELETE_REVIEW_ACTION',


    REVIEW_VERIFY_BATHROOM_QUALITY: 'REVIEW_VERIFY_BATHROOM_QUALITY',
    REVIEW_VERIFY_STAFF_KINDNESS: 'REVIEW_VERIFY_STAFF_KINDNESS',
    REVIEW_VERIFY_CLEANLINESS: 'REVIEW_VERIFY_CLEANLINESS',
    REVIEW_VERIFY_DRIVE_THRU: 'REVIEW_VERIFY_DRIVE_THRU',
    REVIEW_VERIFY_DELIVERY_SPEED: 'REVIEW_VERIFY_DELIVERY_SPEED',
    REVIEW_VERIFY_FOOD_QUALITY: 'REVIEW_VERIFY_FOOD_QUALITY',

    REVIEW_SET_BATHROOM_QUALITY: 'REVIEW_SET_BATHROOM_QUALITY',
    REVIEW_SET_STAFF_KINDNESS: 'REVIEW_SET_STAFF_KINDNESS',
    REVIEW_SET_CLEANLINESS: 'REVIEW_SET_CLEANLINESS',
    REVIEW_SET_DRIVE_THRU: 'REVIEW_SET_DRIVE_THRU',
    REVIEW_SET_DELIVERY_SPEED: 'REVIEW_SET_DELIVERY_SPEED',
    REVIEW_SET_FOOD_QUALITY: 'REVIEW_SET_FOOD_QUALITY',
    REVIEW_SET_PHOTOS: 'REVIEW_SET_PHOTOS',
    REVIEW_PHOTOS: 'REVIEW_PHOTOS',
    REVIEW_SET_DIALOG_STATE: 'REVIEW_SET_DIALOG_STATE',
    REVIEW_SET_BACKDROP_STATE: 'REVIEW_SET_BACKDROP_STATE'
};

export { ReviewsActionsConstants };
