const HomeActionsConstants = {
    LOAD_RESTAURANTS_ACTION: 'LOAD_RESTAURANTS_ACTION',
    LOAD_SUGGESTIONS: 'LOAD_SUGGESTIONS',
    RESET_SUGGESTIONS: 'RESET_SUGGESTIONS',
    LOAD_RESTAURANTS_BY_FILTER_ACTION: 'LOAD_RESTAURANTS_BY_FILTER_ACTION',
    LOAD_RESTAURANTS_BY_FILTER_ACTION_SUCCESS: 'LOAD_RESTAURANTS_BY_FILTER_ACTION_SUCCESS',
    LOAD_RESTAURANTS_BY_FILTER_ACTION_FAILURE: 'LOAD_RESTAURANTS_BY_FILTER_ACTION_FAILURE',
    LOAD_RESTAURANTS_ACTION_SUCCESS: 'LOAD_RESTAURANTS_ACTION_SUCCESS',
    LOAD_RESTAURANTS_ACTION_FAILURE: 'LOAD_RESTAURANTS_ACTION_FAILURE',
    SET_AVERAGE_SELECTION: 'SET_AVERAGE_SELECTION',
    SET_LOCATION_RADIUS: 'SET_LOCATION_RADIUS',
    SET_REST_LOCATION: 'SET_REST_LOCATION',
    SET_REST_LOCATION_SUCCESSFUL: 'SET_REST_LOCATION_SUCCESSFUL'
};

export { HomeActionsConstants };
