const UserSearchActionsConstants = {
    RESET_USERS_SUGGESTIONS: 'RESET_USERS_SUGGESTIONS',
    SET_USERNAME_INPUT: 'SET_USERNAME_INPUT',
    LOAD_USERS_ACTION: 'LOAD_USERS_ACTION',
    LOAD_USERS_ACTION_SUCCESS: 'LOAD_USERS_ACTION_SUCCESS',
    LOAD_USERS_ACTION_FAILURE:  'LOAD_USERS_ACTION_FAIL',
    LOAD_USERS_BY_FILTER_ACTION: 'LOAD_USERS_BY_FILTER_ACTION',
    LOAD_USERS_BY_FILTER_ACTION_SUCCESS: 'LOAD_USERS_BY_FILTER_ACTION_SUCCESS',
    LOAD_USERS_BY_FILTER_ACTION_FAILURE: 'LOAD_USERS_BY_FILTER_ACTION_FAILURE',
    LOAD_USERS_SUGGESTIONS: 'LOAD_USERS_SUGGESTIONS',
};

export { UserSearchActionsConstants };