const LocationActionsConstants = {
    GET_LOCATION_SUGGESTIONS: 'GET_LOCATION_SUGGESTIONS',
    GET_LOCATION_SUGGESTIONS_SUCCESS: 'GET_LOCATION_SUGGESTIONS_SUCCESS',
    GET_LOCATION_SUGGESTIONS_FAIL: 'GET_LOCATION_SUGGESTIONS_FAIL',
    SET_LOCATION_RADIUS_VALUE: 'SET_LOCATION_RADIUS_VALUE',
    SET_LOCATION_SELECTED: 'SET_LOCATION_SELECTED',
    SET_LOCATION_SELECTED_SUCCESS: 'SET_LOCATION_SELECTED_SUCCESS',
    SET_LOCATION_SELECTED_FAIL: 'SET_LOCATION_SELECTED_FAIL',
    CLEAR_LOCATION_SELECTED: 'CLEAR_LOCATION_SELECTED'
};

export { LocationActionsConstants };
