const RestaurantInfoConstants = {
    LOAD_RESTAURANT_INFO_ACTION: 'LOAD_RESTAURANT_INFO_ACTION',
    LOAD_RESTAURANT_INFO_ACTION_SUCCESS: 'LOAD_RESTAURANT_INFO_ACTION_SUCCESS',
    LOAD_RESTAURANT_INFO_ACTION_FAILURE: 'LOAD_RESTAURANT_INFO_ACTION_FAILURE',
};

export { RestaurantInfoConstants };
