const AppMenuActionsConstants = {
    SET_ANCHOR_EL_ACTION: 'SET_ANCHOR_EL_ACTION',
    SET_SEARCH_INPUT: 'SET_SEARCH_INPUT',
    SEARCH_RESTAURANT_ACTION: 'SEARCH_RESTAURANT_ACTION',
    SEARCH_ACTION_SUCCESS: 'SEARCH_ACTION_SUCCESS',
    SEARCH_ACTION_FAIL: 'SEARCH_ACTION_FAIL',
    LOAD_SUGGESTIONS: 'LOAD_SUGGESTIONS'
};

export { AppMenuActionsConstants }
