const UserActionsConstants = {
    LOGIN_ACTION: 'LOGIN_ACTION',
    LOGOUT_ACTION: 'LOGOUT_ACTION',

    SIGN_UP_ACTION: 'SIGN_UP_ACTION',
    SIGN_UP_ACTION_SUCCESS: 'SIGN_UP_ACTION_SUCCESS',
    SIGN_UP_ACTION_ERROR: 'SIGN_UP_ACTION_ERROR',

    SIGN_UP_VERIFY_USERNAME_AVAILABILITY: 'SIGN_UP_VERIFY_USERNAME_AVAILABILITY',
    SIGN_UP_VERIFY_USERNAME_AVAILABILITY_SUCCESS: 'SIGN_UP_VERIFY_USERNAME_AVAILABILITY_SUCCESS',
    SIGN_UP_VERIFY_USERNAME_AVAILABILITY_ERROR: 'USERNAME_FREE_TO_USE',
    SIGN_UP_VERIFY_EMAIL: 'SIGN_UP_VERIFY_EMAIL',
    SIGN_UP_VERIFY_USERNAME: 'SIGN_UP_VERIFY_USERNAME',
    SIGN_UP_VERIFY_PASSWORD: 'SIGN_UP_VERIFY_PASSWORD',

    SIGN_UP_SET_PASSWORD: 'SIGN_UP_SET_PASSWORD',
    SIGN_UP_SET_EMAIL: 'SIGN_UP_SET_EMAIL',
    SIGN_UP_SET_USERNAME: 'SIGN_UP_SET_USERNAME',
    SIGN_UP_SET_PROFILE_PHOTO: 'SIGN_UP_SET_PROFILE_PHOTO',

    GET_USER_PROFILE: 'GET_USER_PROFILE',
    GET_USER_PROFILE_SUCCESS: 'GET_USER_PROFILE_SUCCESS',
    GET_USER_PROFILE_ERROR: 'GET_USER_PROFILE_ERROR',

    EDIT_USERNAME: 'EDIT_USERNAME',
    EDIT_LOCATION: 'EDIT_LOCATION',

    UPDATE_USER: 'UPDATE_USER',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_ERROR: 'UPDATE_USER_ERROR'
};

export { UserActionsConstants }
